<?php

namespace hflan\GuestbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('f')->orderBy('f.createdAt', 'DESC');
    }

    public function findRandomOne()
    {
        $count = $this->count();

        if($count == 0) return null;

        $qb = $this->createQueryBuilder('f')
            ->setMaxResults(1)
            ->setFirstResult(mt_rand(0, $count-1));

        return $qb->getQuery()->getSingleResult();
    }

    public function count()
    {
        return $this->createQueryBuilder('f')->select('COUNT(f)')->getQuery()->getSingleScalarResult();
    }
}
