# Admin

hflan_blog_admin:
    pattern:  /admin/{page}
    defaults: { _controller: hflanBlogBundle:Admin:index, page:1 }
    requirements:
        page: \d+

hflan_blog_new:
    pattern:  /admin/new
    defaults: { _controller: hflanBlogBundle:Admin:new }

hflan_blog_edit:
    pattern:  /admin/edit/{slug}
    defaults: { _controller: hflanBlogBundle:Admin:edit }

hflan_blog_remove:
    pattern:  /admin/remove/{slug}
    defaults: { _controller: hflanBlogBundle:Admin:remove }

hflan_blog_generate:
    pattern:  /admin/generate
    defaults: { _controller: hflanPlayerBundle:Default:generate }

# Public

hflan_blog:
    pattern:  /{page}
    defaults: { _controller: hflanBlogBundle:Public:index, page:1 }
    requirements:
        page: \d+

hflan_blog_show:
    pattern:  /{slug}
    defaults: { _controller: hflanBlogBundle:Public:show }