<?php

namespace hflan\LanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExtraFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraFieldRepository extends EntityRepository
{
    public function getExtraFieldsArray(Tournament $tournament)
    {
        $qb = $this->createQueryBuilder('e')
            ->where('e.tournament = :tournament')
            ->setParameter('tournament', $tournament);

        $array = array();

        foreach($qb->getQuery()->getResult() as $extraField){
            $array[$extraField->getName()] = '';
        }

        return $array;
    }
}
