<?php

namespace hflan\LanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExtraFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraFieldRepository extends EntityRepository
{
}
