<?php

namespace hflan\LanBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function emails($teams)
    {
        if(!count($teams))
            return array();

        $qb = $this->createQueryBuilder('p')
            ->select('p.email')
            ->where('p.team IN (:teams)')
            ->setParameter('teams', $teams)
            ->andWhere('p.email is not NULL');

        return array_map(function($result){ return $result['email']; }, $qb->getQuery()->getResult(Query::HYDRATE_ARRAY));
    }
}
