<?php

namespace hflan\LanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function findTeamRegistrationData(Tournament $tournament)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('COUNT(t), t.paid, t.infoLocked')
            ->where('t.tournament = :tournament')
            ->setParameter('tournament', $tournament)
            ->groupBy('t.paid, t.infoLocked');

        return $qb->getQuery()->getResult();
    }
}
