<?php

namespace hflan\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function findAll($locale = null)
    {
        $qb = $this->createQueryBuilder('a')->orderBy('a.sortIndex', 'ASC');

        if($locale !== null) $qb->where('a.lang = :lang')->setParameter('lang', $locale);

        return $qb->getQuery()->getResult();
    }
}
