<?php

namespace hflan\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('a')->orderBy('a.createdAt', 'DESC');
    }
}
